#!/usr/bin/env bash
# PostToolUse(Edit|Write|MultiEdit): say what the edit just committed you to,
# while you still remember writing it (spec: kb.harness.hooks, advisory).
#
# Some mistakes are silent at the keyboard and loud in `make validate` later,
# when re-earning the context costs more than the fix:
#
#   1. hand-editing a stamped file — its generator's `--check` reports the drift;
#   2. editing a file in an ignored output folder — the next run replaces it;
#   3. editing a data file without the command that reads it;
#   4. editing a skill, an agent or a rule without the two gates that hold
#      their shape and their links;
#   5. pushing a context layer to within ADVISORY_MARGIN words of its budget,
#      or past it (docs/concepts/context-layering.md).
#
# None is a reason to stop: each is legitimate work one command away from
# right. So this hook only advises. It never blocks, never writes, never
# reaches the network, and always exits 0. It reads the edited path off the
# payload, prints what that path owes as one JSON object whose two note fields
# carry the same text, and is otherwise silent: on a hand-written page, a
# program source, a missing file, a path outside the project and any payload
# it cannot read.
#
# Adding a case: a function that calls `note`, called at the bottom. Name the
# command to run, not the concept behind it.
set -uo pipefail

payload="$(cat 2>/dev/null || true)"
command -v jq >/dev/null 2>&1 || exit 0

file="$(printf '%s' "$payload" |
  jq -r 'if type == "object" then (.tool_input.file_path // "") else "" end' 2>/dev/null || true)"
[ -n "$file" ] || exit 0

root="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || true)}"
[ -n "$root" ] || exit 0

# Repo-relative, so every note reads like a path in the tree. An edit outside
# the checkout is none of this hook's business.
case "$file" in
  "$root"/*) rel="${file#"$root"/}" ;;
  /*) exit 0 ;;
  *) rel="$file" ;;
esac
abs="$root/$rel"
[ -f "$abs" ] || exit 0

NOTES=""
note() {
  NOTES="${NOTES}${NOTES:+
}[after-write] $1"
}

# ---------------------------------------------------------------------------
# 1. A stamped file. The generator is read off the file's own stamp, so a
#    generator added tomorrow is covered tomorrow. The whole file is searched,
#    since a stamp below frontmatter is still a stamp, but only a line that is
#    the stamp alone, outside a fence, counts: a page quoting the stamp text in
#    prose or in an example is still hand-written. Only a whole-file stamp
#    counts, too: a hand-written page holding a generated block (the triage
#    page) stamps only that block, and the block's freshness gate owns it. The
#    repair command is the `fix` of the registry row that runs the generator
#    with `--check`.
# ---------------------------------------------------------------------------
check_stamped() {
  local stamp gen src fix
  # The prerequisite reference page is built from the relations file and the
  # pages' titles and descriptions at once, so the note names both.
  case "$rel" in
    docs/reference/prerequisites.md)
      note "docs/reference/prerequisites.md is GENERATED by tools/src/gen/gen-prerequisites.ts from docs/data/relations.json and the pages' titles and descriptions; the prerequisites-fresh gate fails a hand edit. Edit docs/data/relations.json (node scripts/kb.mjs link or unlink write whole edges), or a title or description on its page, instead, then run: make gen && make gate G=check-prerequisites"
      return 0
      ;;
  esac
  stamp="$(awk '
    /^[[:space:]]*(```|~~~)/ { fenced = !fenced; next }
    !fenced && /^[[:space:]]*(<!--|\/\/|#|\/\*)[[:space:]]*GENERATED by [^ ]+ from [^ ]+\. Do not edit this file\.[[:space:]]*(-->|\*\/)?[[:space:]]*$/ { print; exit }
  ' "$abs" 2>/dev/null || true)"
  [ -n "$stamp" ] || return 0
  gen="$(printf '%s' "$stamp" | sed -E 's/.*GENERATED by ([^ ]+) from .*/\1/')"
  src="$(printf '%s' "$stamp" | sed -E 's/.*GENERATED by [^ ]+ from ([^ ]+)\. Do not edit this file\..*/\1/')"
  fix="$(jq -r --arg g "$gen --check" \
    'first(.gates[]? | select(((.wired // "") + " " + (.local_command // "")) | contains($g)) | .fix) // ""' \
    "$root/docs/data/gates.json" 2>/dev/null || true)"
  if [ -n "$fix" ]; then
    note "$rel is GENERATED by $gen from $src. Edit $src instead, then run: $fix"
  else
    note "$rel is GENERATED by $gen from $src. Edit the generator's source or $src instead, never this file."
  fi
}

# ---------------------------------------------------------------------------
# 2. An ignored output folder: the next run replaces whatever was edited.
# ---------------------------------------------------------------------------
check_output() {
  case "$rel" in
    tools/coverage/*)
      note "$rel is coverage output, rebuilt by \`make tools-test\` and never committed; your edit will not survive the next run. Run: make tools-test"
      ;;
    site/coverage/*)
      note "$rel is coverage output, rebuilt by \`make site-test\` and never committed; your edit will not survive the next run. Run: make site-test"
      ;;
    site/dist/* | site/.astro/* | site/node_modules/.astro/* | site/public/kb.js)
      note "$rel is output of the site build, never committed; the next build replaces it. Change the page under docs/, the site workspace or tools/src/site/ instead, then run: make site-build"
      ;;
    site/src/content/docs/map/*.mdx) # the map area's page, before the hub case that would claim an index.mdx
      note "$rel is a map page tools/src/site/gen-map-pages.ts writes on every site build from docs/data/site-structure.json, never committed. Change that generator or the components it places instead, then run: make site-build"
      ;;
    site/src/content/docs/*/*index.mdx) # a hub below the top folder; the top index.mdx is hand-written
      note "$rel is a hub tools/src/site/gen-site-hubs.ts writes on every site build from docs/data/site-structure.json and its pages' frontmatter, never committed. Change those instead, then run: make site-build"
      ;;
    site/src/content/docs/*.md)
      note "$rel is the copy tools/src/site/gen-site-docs.ts mirrors from docs/ on every site build, never committed. Change the page under docs/ instead, then run: make site-build"
      ;;
  esac
}

# ---------------------------------------------------------------------------
# 3. A data file. Each names what reads it and the command to run, written
#    out because the coupling is the fact worth knowing. Every file under docs/data/ needs its own case here; the suite
#    fails when one has none. Each of them also owes the json-sanity gate its
#    source header (version, updated, note), so each command ends with it.
# ---------------------------------------------------------------------------
check_data() {
  case "$rel" in
    docs/data/gates.json)
      note "docs/data/gates.json is read by tools/src/gen/gen-gates.ts (docs/reference/gates.md and the triage page's generated blocks), by the driver behind \`make validate\`, and by the gates-sync gate, which holds it to the Makefile, the workflow and the triage page; json-sanity holds its source header. Run: make gates && make gate G=check-gates-sync && make gate G=check-json"
      ;;
    docs/data/allow/test-colocation.json)
      note "docs/data/allow/test-colocation.json is the test-colocation gate's allowlist; an entry needs a reason and must excuse something, and json-sanity holds its source header. Run: make gate G=check-test-colocation && make gate G=check-json"
      ;;
    docs/data/allow/vocabulary.json)
      note "docs/data/allow/vocabulary.json is the vocabulary gate's allowlist: an entry excuses the banned phrasings in the files it matches, needs a reason, an owner and a since date (a banned phrasing is a failure, never a category), and must excuse something; json-sanity holds its source header. Run: make gate G=check-vocabulary && make gate G=check-json"
      ;;
    docs/data/allow/context-layers.json)
      note "docs/data/allow/context-layers.json is the context-layers gate's placement allowlist; an entry needs owner, since and reason, and must excuse something, and json-sanity holds its source header. Run: make gate G=check-claude-md && make gate G=check-json"
      ;;
    docs/data/allow/harness-shape.json)
      note "docs/data/allow/harness-shape.json is the harness-shape gate's allowlist: it ships empty, an entry excuses one skill's shape findings, needs owner, since and reason, and must excuse something; json-sanity holds its source header. Run: make gate G=check-harness && make gate G=check-json"
      ;;
    docs/data/allow/prerequisites.json)
      note "docs/data/allow/prerequisites.json is the prerequisites gate's orphan allowlist, matched against a record's route; an entry needs a reason and must excuse something, and json-sanity holds its source header. Run: make gate G=check-prerequisites && make gate G=check-json"
      ;;
    docs/data/prerequisites.json)
      note "docs/data/prerequisites.json is GENERATED by tools/src/gen/gen-prerequisites.ts from docs/data/relations.json, the pages' titles and descriptions and docs/data/site-structure.json; the prerequisites-fresh gate fails a hand edit, the prerequisites gate holds the graph, and json-sanity holds its source header. Change the edge in relations.json instead (node scripts/kb.mjs link and unlink write whole edges), then run: make prerequisites && make gate G=check-prerequisites && make gate G=check-json"
      ;;
    docs/data/allow/tags.json)
      note "docs/data/allow/tags.json is the tags gate's allowlist: an entry excuses only the facet findings (order, topic count) of the pages a retag batch has not reached, needs owner, since and reason, and must excuse something; json-sanity holds its source header. Run: make gate G=check-tags && make gate G=check-json"
      ;;
    docs/data/allow/site-hooks.json)
      note "docs/data/allow/site-hooks.json is the site-hooks gate's allowlist: a data-kb-* hook the site's markup emits for a reader of the built page, which no program reads; an entry needs a reason and must excuse something, and json-sanity holds its source header. Run: make gate G=check-site-hooks && make gate G=check-json"
      ;;
    docs/data/allow/site-e2e.json)
      note "docs/data/allow/site-e2e.json is the site-e2e gate's allowance: one entry per reader flow that skips on purpose, with its count and a reason; the gate fails a skip with no entry, a count above its allowance and an allowance above the skips that happen, and json-sanity holds its source header. Run: make site-e2e && make gate G=check-json"
      ;;
    docs/data/allow/site-a11y.json)
      note "docs/data/allow/site-a11y.json is the site-accessibility gate's ratchet: bandMax is the most pages allowed in the chrome-share warning band, and it only goes down. Run: make gate G=check-site-a11y && make gate G=check-json"
      ;;
    docs/data/allow/kb-shape.json)
      note "docs/data/allow/kb-shape.json is the kb-shape gate's allowlist: each entry names one page and the ratchet it covers (explain: a missing example or a word bound, costs: a pattern's missing costs list, KB-014; description: a block over 80 words or in several paragraphs, held to its maxWords, KB-015), needs owner, since and reason, and must excuse something; a new page is never listed; json-sanity holds its source header. Run: make gate G=check-kb-shape && make gate G=check-json"
      ;;
    # The single sources the blocks, the reference pages and the site are built from.
    docs/data/site-structure.json)
      note "docs/data/site-structure.json is the structure file: the hub generator, gen-map (the docs map) and the structure gate read it, the kb-shape gate holds each page's area to its row, and AREAS in site/src/lib/types.ts lists its area ids in order; json-sanity holds its source header. Move a page's row with its learning-paths.json stages in the same change. Run: make gen && make gate G=check-site-structure && make gate G=check-json"
      ;;
    docs/data/tags.json)
      note "docs/data/tags.json is the closed tag list: gen-taxonomy renders docs/reference/tags.md from it, the tags gate holds every page and the TAGS tuple in site/src/lib/types.ts to it, and json-sanity holds its source header. Run: make gen && make gate G=check-tags && make gate G=check-json"
      ;;
    docs/data/content-model.json)
      note "docs/data/content-model.json is the page shape the kb-shape and relations gates read, with the verb labels gen-relations renders and the dialect constants in tools/src/lib/kb-attrs.ts that must agree with it; json-sanity holds its source header. Run: make gen && make gate G=check-kb-shape && make gate G=check-json"
      ;;
    docs/data/glossary.json)
      note "docs/data/glossary.json is the glossary: the vocabulary gate bans every avoid phrasing in markdown prose, gen-vocabulary renders docs/reference/glossary.md from it, and json-sanity holds its source header. Run: make gen && make gate G=check-vocabulary && make gate G=check-json"
      ;;
    docs/data/products.json)
      note "docs/data/products.json is the product registry: the products gate holds it to the capability pages' mapping tables, the site's stack index links through it, and json-sanity holds its source header. Fetch a URL before adding it. Run: make gate G=check-products && make gate G=check-json"
      ;;
    docs/data/stack.json)
      note "docs/data/stack.json says which dashes on the stack index (map/stack.html) are verdicts: a band note, or one pattern's reason no cloud sells it. buildStack in tools/src/lib/site-map.ts reads it and refuses an entry an implements edge contradicts; json-sanity holds its source header. Run: make gate G=check-json && make tools-test T=site-map && make site-build"
      ;;
    docs/data/search-synonyms.json)
      note "docs/data/search-synonyms.json is the search synonym bridge: kb.mjs find reads it, the search-synonyms gate holds its rules, docs/reference/search-synonyms.md is rendered from it, and json-sanity holds its source header. Run: make synonyms && make gate G=check-search-synonyms && make gate G=check-json && make tools-test T=relevance"
      ;;
    docs/data/search-oracle.json)
      note "docs/data/search-oracle.json holds the queries the search must answer: the search-oracle gate runs each through the search box's ranking and through kb.mjs find, and json-sanity holds its source header. A missed query is recorded here first. Run: make gate G=check-search-oracle && make gate G=check-json"
      ;;
    docs/data/relations.json)
      note "docs/data/relations.json holds every typed edge: gen-relations splices each page's relationships block from it, gen-prerequisites builds docs/data/prerequisites.json from it, the relations gate holds every edge closed and paired, and json-sanity holds its source header. node scripts/kb.mjs link and unlink write whole edges. Run: make gen && make gate G=check-relations && make gate G=check-json"
      ;;
    docs/data/learning-paths.json)
      note "docs/data/learning-paths.json holds the theme tours: gen-tours renders each theme's tour block and each member's fluency block from it, the learning-paths gate holds every stage to a route the structure file produces, and json-sanity holds its source header. Run: make gen && make gate G=check-learning-paths && make gate G=check-json"
      ;;
    docs/data/tracks.json)
      note "docs/data/tracks.json holds the Start-here tracks and the tier of each page a track stages: site/src/lib/tracks.ts reads it for the home page, the tracks gate holds every track to published, non-draft theme pages and every tier to a legal value, and json-sanity holds its source header. Edited by hand. Run: make gate G=check-tracks && make gate G=check-json"
      ;;
    tools/src/kb/spec.ts)
      note "tools/src/kb/spec.ts is the kb.mjs command surface: node scripts/kb.mjs prints its usage from it, and the skills and agents name its commands and flags. Run: make tools-test T=kb/spec && make gate G=check-harness-routes"
      ;;
  esac
}

# ---------------------------------------------------------------------------
# 4. A skill, an agent or a rule. The harness-shape and harness-routes gates
#    hold its shape and its links. A malformed SKILL.md fails to register
#    without a word, so the edit names both while it is fresh.
# ---------------------------------------------------------------------------
check_harness() {
  case "$rel" in
    .claude/worktrees/*) ;;
    .claude/*.md)
      note "$rel is read by the harness-shape gate, which holds its shape, and by the harness-routes gate, which holds its links. Run: make gate G=check-harness && make gate G=check-harness-routes"
      ;;
  esac
}

# ---------------------------------------------------------------------------
# 5. A context layer. The budgets and the margin are read out of the layer
#    gate at run time, so this hook holds no copy of them; when it cannot read
#    them, it says nothing. A nested layer is measured in lines, by the gate.
# ---------------------------------------------------------------------------
gate_const() { # <name> -> the value `export const <name> = N;` holds in the layer gate
  sed -n "s/^export const $1 = \([0-9][0-9]*\);.*/\1/p" "$root/tools/src/gates/check-claude-md.ts" 2>/dev/null | head -n 1
}

check_layer() {
  local budget margin words
  case "$rel" in
    CLAUDE.md) budget="$(gate_const ROOT_BUDGET)" ;;
    */*/CLAUDE.md) return 0 ;;
    */CLAUDE.md) budget="$(gate_const LAYER_BUDGET)" ;;
    *) return 0 ;;
  esac
  margin="$(gate_const ADVISORY_MARGIN)"
  [ -n "$budget" ] && [ -n "$margin" ] || return 0

  words="$(wc -w < "$abs" 2>/dev/null | tr -d ' ')"
  [ -n "$words" ] || return 0
  # From the margin below the budget, the margin included (hooks-C4).
  if [ "$words" -gt "$budget" ]; then
    note "$rel is now $words words, over its $budget budget, so make gate G=check-claude-md will fail. Move a line to its single source and leave a link (docs/concepts/context-layering.md)."
  elif [ "$words" -ge $((budget - margin)) ]; then
    note "$rel is now $words/$budget words: the next fact added here must displace one to its single source. Check it with: make gate G=check-claude-md"
  fi
}

check_stamped
check_output
check_data
check_harness
check_layer

[ -n "$NOTES" ] || exit 0

# additionalContext reaches the session; systemMessage reaches the person at
# the keyboard. Both, with the same text, because either alone leaves one out.
jq -nc --arg n "$NOTES" \
  '{hookSpecificOutput:{hookEventName:"PostToolUse",additionalContext:$n},systemMessage:$n}' 2>/dev/null
exit 0
