/**
 * The map area's generator (spec mirror-and-hubs-C8: a `generated` area's
 * hub and pages are its own generator's; kb.generation.output-ownership for
 * what it may overwrite or delete).
 */

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { expectFail, expectMisuse, expectPass, makeSandbox, type Sandbox } from '../lib/sandbox.js';
import type { Structure } from '../lib/site-routes.js';
import { GENERATOR, MAP_PAGE_TEXT, mapStamp, renderMapPage, spec } from './gen-map-pages.js';
import { docsTree, STRUCTURE } from './site-fixtures.js';
import { CONTENT } from './site-output.js';

let sb: Sandbox;
beforeEach(() => {
  sb = makeSandbox();
});
afterEach(() => sb.cleanup());

const MAP = {
  id: 'map',
  label: 'From Pattern to Product',
  nav: 'link' as const,
  generated: GENERATOR,
  hub: { description: 'Two views across it all', intro: 'Read across, not down: {both} views.', tags: ['composition', 'cloud'] },
  pages: [
    { slug: 'stack', label: 'From Pattern to Product', source: 'generated', route: '/map/stack.html' },
  ],
};

const WITH_MAP: Structure = { areas: [...STRUCTURE.areas, MAP] };

describe('gen-map-pages', () => {
  it('writes the stack page, stamped, with its page keys, and no hub', async () => {
    docsTree(sb, WITH_MAP);
    const r = await sb.run(spec);
    expectPass(r);
    expect(r.out).toBe('[gen-map-pages] wrote 1 map pages from docs/data/site-structure.json');

    // The stack index: one heading per band holding a pattern, each with its own instance.
    const stack = sb.read(`${CONTENT}/map/stack.mdx`);
    expect(stack.split('\n').slice(0, 9)).toEqual([
      '---',
      'title: From Pattern to Product',
      // A colon in the text: the scalar is quoted.
      `description: "${MAP_PAGE_TEXT['stack']?.description as string}"`,
      'area: map',
      'owner: Oleksandr Derechei',
      'tags: [cloud, integration]',
      // Every input page declares a status (maturity-C3).
      'status: stable',
      // The comma makes the value one YAML quotes.
      `source: "generated by ${GENERATOR} from docs/data/relations.json, docs/data/stack.json and the capability pages"`,
      '---',
    ]);
    expect(stack).toContain(`${mapStamp('docs/data/relations.json, docs/data/stack.json and the capability pages')}\n`);
    // The stack index keeps its rail: it lists the bands.
    expect(stack).not.toContain('tableOfContents');
    expect(stack).toContain("import StackIndex from '../../../components/StackIndex/StackIndex.astro';");
    expect(stack).toContain('<StackIndex />\n\n## Caching\n\n<StackIndex band="caching" />\n');
    expect(sb.exists(`${CONTENT}/map/index.mdx`)).toBe(false);
  });

  it('writes nothing and says so when no area names it', async () => {
    docsTree(sb);
    const r = await sb.run(spec);
    expectPass(r);
    expect(r.out).toBe('[gen-map-pages] wrote 0 map pages from docs/data/site-structure.json');
    expect(r.err).toBe(`[gen-map-pages] note: no area in docs/data/site-structure.json names ${GENERATOR} as its generator — no map pages written`);
    expect(sb.exists(`${CONTENT}/map`)).toBe(false);
  });

  it('names a row it has no words for, and writes nothing', async () => {
    docsTree(sb, { areas: [...STRUCTURE.areas, { ...MAP, pages: [...MAP.pages, { slug: 'atlas', label: 'Atlas', source: 'generated', route: '/map/atlas.html' }] }] });
    const r = await sb.run(spec);
    expectFail(r, `docs/data/site-structure.json: area "map" lists "atlas", which ${GENERATOR} has no page for`);
    expect(sb.exists(`${CONTENT}/map`)).toBe(false);
  });

  it('writes nothing for an area with no rows', async () => {
    docsTree(sb, { areas: [...STRUCTURE.areas, { ...MAP, pages: [] }] });
    const r = await sb.run(spec);
    expectPass(r);
    expect(r.out).toBe('[gen-map-pages] wrote 0 map pages from docs/data/site-structure.json');
    expect(sb.exists(`${CONTENT}/map/index.mdx`)).toBe(false);
  });

  it('leaves a hand-written file alone with one note, and deletes a stamped file it does not want, a hub included', async () => {
    docsTree(sb, WITH_MAP);
    expectPass(await sb.run(spec));
    sb.write(`${CONTENT}/map/index.mdx`, `${mapStamp('docs/data/site-structure.json')}\n`);
    sb.write(`${CONTENT}/map/notes.mdx`, '---\ntitle: Notes\n---\n\nNot stamped, not wanted.\n');
    sb.write(`${CONTENT}/map/stack.mdx`, '---\ntitle: Stack\n---\n\nWritten by hand.\n');
    const r = await sb.run(spec);
    expectPass(r);
    expect(r.err).toBe(`[gen-map-pages] note: ${CONTENT}/map/stack.mdx is hand-written — leaving it alone`);
    expect(sb.read(`${CONTENT}/map/stack.mdx`)).toContain('Written by hand.');
    expect(sb.exists(`${CONTENT}/map/notes.mdx`)).toBe(true);
    expect(sb.exists(`${CONTENT}/map/index.mdx`)).toBe(false);
  });

  it('exits 2 on an argument, writing nothing', async () => {
    docsTree(sb, WITH_MAP);
    const r = await sb.run(spec, ['--nope']);
    expectMisuse(r);
    expect(r.out).toBe('');
    expect(sb.exists(`${CONTENT}/map`)).toBe(false);
  });
});

describe('rendering', () => {
  const stack = MAP_PAGE_TEXT['stack'] as (typeof MAP_PAGE_TEXT)[string];

  it('climbs from a nested folder to site/src for its imports', () => {
    const page = renderMapPage(WITH_MAP, MAP, 'patterns/map', 'Stack', stack);
    expect(page).toContain("import StackIndex from '../../../../components/StackIndex/StackIndex.astro';");
  });

  it('escapes a lead paragraph as MDX text', () => {
    const text = { ...stack, lead: ['A <b> & {c}'] };
    expect(renderMapPage(WITH_MAP, MAP, 'map', 'Stack', text)).toContain('\nA &lt;b> &amp; \\{c\\}\n');
  });

  it('drops the rail of a page that asks for none', () => {
    expect(renderMapPage(WITH_MAP, MAP, 'map', 'Stack', { ...stack, toc: false })).toContain('\ntableOfContents: false\n');
  });
});
