/**
 * The map area's page, written whole: the pattern-to-product index. The area
 * is a `link` area (docs/data/site-structure.json `nav`): one page, one
 * top-level sidebar link and no hub, so this generator writes no hub
 * (spec mirror-and-hubs-C8: a `generated` area's pages come from its own
 * generator; the area itself is a hand-edited entry of the structure file).
 *
 * Runs in the site's `prebuild`, after the mirror and the hubs. For the area
 * of docs/data/site-structure.json whose `generated` names this file it writes,
 * under `site/src/content/docs/<area>/`:
 *
 *   <slug>.mdx  one page per row: frontmatter with the page keys and a
 *               `source` naming this generator, the stamp, a lead paragraph,
 *               then the one component that draws the page from the data
 *               files at build time — StackIndex for `stack`.
 *
 * Each page's words are here (`MAP_PAGE_TEXT`): the page is built by this
 * script, so there is no page under docs/ to copy them from. A row this file
 * has no words for is a finding naming it, and nothing is written.
 *
 * Build output, like the mirror and the hubs: ignored by git, rebuilt on every
 * build, never checked. A file this generator did not stamp is noted and left
 * alone (output-ownership-C3); a stamped file it no longer wants, a hub
 * included, is deleted. A structure file with no map area writes nothing and
 * says so.
 *
 * Usage: gen-map-pages   (no arguments)
 */

import fs from 'node:fs';
import path from 'node:path';

import { yamlInlineList, yamlScalar } from '../lib/frontmatter.js';
import { STAMP_PREFIX } from '../lib/generated.js';
import { main, type GateContext, type GateSpec } from '../lib/gate.js';
import { patternBands } from '../lib/site-map.js';
import { areaFolder, placedPages, type Structure, type StructureArea } from '../lib/site-routes.js';
import { mdxText } from './gen-site-hubs.js';
import { CONTENT, generatedFiles, readStructure, removeEmptyDirs, SITE_OWNER, STRUCTURE } from './site-output.js';

export const GENERATOR = 'tools/src/site/gen-map-pages.ts';

/** What one map page says, and the component that draws the rest. */
export interface MapPageText {
  readonly description: string;
  readonly tags: readonly string[];
  /** What the page is built from, for its `source` key and its stamp. */
  readonly from: string;
  /** The lead paragraphs, above the component. */
  readonly lead: readonly string[];
  /** The component folder and file under site/src/components. */
  readonly component: string;
  /**
   * False for a page that is one wide canvas with no headings to list: its
   * "On this page" rail would hold one entry and take a third of the width
   * the canvas needs (`tableOfContents: false` in its frontmatter).
   */
  readonly toc: boolean;
  /**
   * The body under the lead: the component, and for the stack index one
   * markdown heading per band with the band's own instance under it, so the
   * page's table of contents lists the bands.
   */
  readonly body: (structure: Structure, name: string) => readonly string[];
}

export const MAP_PAGE_TEXT: Readonly<Record<string, MapPageText>> = {
  stack: {
    description: 'Every pattern against the cloud service that sells it: AWS, Azure, Google Cloud and the open-source alternative, taken from the capability pages.',
    tags: ['cloud', 'integration'],
    from: 'docs/data/relations.json, docs/data/stack.json and the capability pages',
    lead: [
      'Every pattern in the knowledge base has a row. Where a cloud sells the pattern ready-made, the cells name the product, and the small line under the pattern links the capability row those products come from.',
      'A dash means this index records no product. Where the band note or the line under the pattern says so, none exists, because the pattern is code you write rather than a service you rent. Any other dash is a mapping not written yet: a gap in the index, not a claim about the market.',
    ],
    component: 'StackIndex/StackIndex.astro',
    toc: true,
    body: (structure, name) => [
      `<${name} />`,
      '',
      ...patternBands(structure).flatMap((band) => [`## ${mdxText(band.label)}`, '', `<${name} band="${band.id}" />`, '']),
    ],
  },
};

/** The stamp every file here opens with, in MDX's comment syntax (output-ownership-C2). */
export function mapStamp(from: string): string {
  return `{/* ${STAMP_PREFIX} ${GENERATOR} from ${from}. Do not edit this file. */}`;
}

/** Frontmatter a generated page carries: the page keys (status stable: maturity-C3), then its source, then its rail when it has none. */
function head(title: string, description: string, area: string, tags: readonly string[], from: string, toc = true): string[] {
  return [
    '---',
    `title: ${yamlScalar(title)}`,
    `description: ${yamlScalar(description)}`,
    `area: ${area}`,
    `owner: ${yamlScalar(SITE_OWNER)}`,
    `tags: ${yamlInlineList(tags)}`,
    'status: stable',
    `source: ${yamlScalar(`generated by ${GENERATOR} from ${from}`)}`,
    ...(toc ? [] : ['tableOfContents: false']),
    '---',
    '',
  ];
}

/** `../` from a file in the area's folder up to site/src. */
const upToSrc = (folder: string): string => '../'.repeat(folder.split('/').length + 2);

/** One map page. */
export function renderMapPage(structure: Structure, area: StructureArea, folder: string, title: string, text: MapPageText): string {
  const name = path.posix.basename(text.component, '.astro');
  return [
    ...head(title, text.description, area.id, text.tags, text.from, text.toc),
    mapStamp(text.from),
    '',
    `import ${name} from '${upToSrc(folder)}components/${text.component}';`,
    '',
    ...text.lead.flatMap((p) => [mdxText(p), '']),
    ...text.body(structure, name),
  ].join('\n');
}

const stamped = (file: string): boolean => fs.readFileSync(file, 'utf8').includes(`${STAMP_PREFIX} ${GENERATOR} `);

export const spec: GateSpec = {
  name: 'gen-map-pages',
  usage: 'usage: gen-map-pages   (no arguments)',
  run(ctx: GateContext): string {
    const structure = readStructure(ctx.root);
    const areas = structure.areas.filter((a) => a.generated === GENERATOR);
    const placed = placedPages(structure);
    const content = path.join(ctx.root, CONTENT);

    const wanted = new Map<string, string>();
    for (const area of areas) {
      const folder = areaFolder(structure, area.id);
      for (const p of placed.filter((x) => x.area === area.id)) {
        const text = MAP_PAGE_TEXT[p.slug];
        if (text === undefined) {
          ctx.fail(STRUCTURE, `area "${area.id}" lists "${p.slug}", which ${GENERATOR} has no page for — add its words to MAP_PAGE_TEXT, or take the row out`);
          continue;
        }
        wanted.set(`${p.route.slice(1, -'.html'.length)}.mdx`, renderMapPage(structure, area, folder, p.label, text));
      }
    }
    if (ctx.findings > 0) return '';

    // What an earlier build wrote and this one does not want goes first.
    for (const rel of generatedFiles(ctx.root, CONTENT)) {
      const inContent = rel.slice(CONTENT.length + 1);
      if (rel.endsWith('.mdx') && !wanted.has(inContent) && stamped(path.join(ctx.root, rel))) fs.rmSync(path.join(ctx.root, rel));
    }
    removeEmptyDirs(content);

    if (areas.length === 0) ctx.note(`note: no area in ${STRUCTURE} names ${GENERATOR} as its generator — no map pages written`);
    let written = 0;
    for (const [rel, text] of wanted) {
      const out = path.join(content, rel);
      if (fs.existsSync(out) && !stamped(out)) {
        ctx.note(`note: ${CONTENT}/${rel} is hand-written — leaving it alone`);
        continue;
      }
      fs.mkdirSync(path.dirname(out), { recursive: true });
      fs.writeFileSync(out, text);
      written += 1;
    }
    return `[gen-map-pages] wrote ${written} map pages from ${STRUCTURE}`;
  },
};

main(spec, import.meta.url);
