/**
 * Text surgery on one page, for kb.mjs v2's writers: the frontmatter block
 * rewritten key by key, a block put in, replaced or taken out, and the
 * whole-file stamp that marks a page no writer may touch. Everything here is
 * a pure function of the page's text; tools/src/kb/write.ts reads and writes
 * the files.
 *
 * The frontmatter is never parsed here. Its values come from the one parser
 * (scripts/fm-json.sh, through tools/src/lib/frontmatter.ts) exactly as
 * written; an untouched key keeps its bytes, a changed key is printed by the
 * one printer (`yamlScalar`, `yamlInlineList`), and a new key goes where the
 * dialect's order puts it (D-10).
 */

import { yamlInlineList, yamlScalar } from '../lib/frontmatter.js';
import { STAMP_PREFIX } from '../lib/generated.js';
import { parseKb, readKb, type Heading } from '../lib/kb-attrs.js';

import { KbError } from './corpus.js';
import { FRONTMATTER } from './page.js';

/** The frontmatter keys in the order the dialect prints them (D-10). */
export const FM_ORDER = ['title', 'description', 'area', 'owner', 'tags', 'status', 'aliases', 'solves', 'favourite', 'source'] as const;

/** A frontmatter change: a scalar, an inline list, `true` for a flag, or null to drop the key. */
export type FmChange = string | readonly string[] | true | null;

/**
 * A page's text split into its frontmatter block (fences and closing newline
 * included) and the rest. The fences are read as the one parser reads them
 * (scripts/lib-frontmatter.sh): `---` with trailing blanks allowed, LF or CRLF.
 */
export function splitFrontmatter(text: string): { fm: string; body: string } {
  const m = FRONTMATTER.exec(text);
  return m === null ? { fm: '', body: text } : { fm: m[0], body: text.slice(m[0].length) };
}

/** The line ending a frontmatter block is written with: CRLF when its first line ends so. */
export function eolOf(fm: string): '\n' | '\r\n' {
  return /^[^\n]*\r\n/.test(fm) ? '\r\n' : '\n';
}

/** The first line of a frontmatter block that is not a one-line `key: value`, or null. */
export function fmShapeProblem(fm: string): string | null {
  const lines = fm.replace(/\r?\n$/, '').split(/\r?\n/).slice(1, -1);
  return lines.find((l) => !/^[A-Za-z_][A-Za-z0-9_-]*:(?: .*)?$/.test(l)) ?? null;
}

function printEntry(key: string, value: string | readonly string[] | true): string {
  if (value === true) return `${key}: true`;
  return `${key}: ${typeof value === 'string' ? yamlScalar(value) : yamlInlineList(value)}`;
}

/**
 * The frontmatter block with `changes` applied. `raw` is the parser's answer
 * for the block, every value exactly as written, in file order: an untouched
 * key is printed back as `key: <raw>`, a changed one by the printer, a
 * dropped one not at all, and a new one after the last key that precedes it
 * in FM_ORDER (a key outside FM_ORDER goes last). Every line ends with `eol`,
 * so a CRLF page keeps its line ending.
 */
export function rewriteFrontmatter(raw: Readonly<Record<string, string>>, changes: ReadonlyMap<string, FmChange>, eol: '\n' | '\r\n' = '\n'): string {
  const keys = Object.keys(raw);
  const rank = (k: string): number => {
    const i = (FM_ORDER as readonly string[]).indexOf(k);
    return i === -1 ? FM_ORDER.length : i;
  };
  for (const [k, v] of changes) {
    if (v === null || keys.includes(k)) continue;
    const after = keys.map((x, i) => ({ x, i })).filter(({ x }) => rank(x) <= rank(k));
    keys.splice(after.length === 0 ? 0 : (after[after.length - 1] as { i: number }).i + 1, 0, k);
  }
  const lines: string[] = [];
  for (const k of keys) {
    const change = changes.get(k);
    if (change === null) continue;
    lines.push(change === undefined ? (raw[k] === '' ? `${k}:` : `${k}: ${raw[k] as string}`) : printEntry(k, change));
  }
  return `---${eol}${lines.join(eol)}${eol}---${eol}`;
}

const FILE_STAMP = new RegExp(`^<!-- ${STAMP_PREFIX} (\\S+) from (\\S+)\\. Do not edit this file\\. -->$`);

/**
 * The generator and source a whole-file stamp names, or null: a stamp on a
 * line of its own, outside a fence, anywhere in the file (output-ownership-C4).
 */
export function stampOf(text: string): { generator: string; source: string } | null {
  let fence: string | null = null;
  for (const line of text.split('\n')) {
    const f = /^[ \t]*(`{3,}|~{3,})/.exec(line);
    if (f !== null) {
      const run = f[1] as string;
      if (fence === null) fence = run;
      else if (run[0] === fence[0] && run.length >= fence.length && line.trim() === run) fence = null;
      continue;
    }
    const m = fence === null ? FILE_STAMP.exec(line) : null;
    if (m !== null) return { generator: m[1] as string, source: m[2] as string };
  }
  return null;
}

/** Refuse a page a generator owns: one that carries a whole-file stamp. */
export function refuseStamped(source: string, text: string): void {
  const s = stampOf(text);
  if (s === null) return;
  throw new KbError(`${source} is generated by ${s.generator} from ${s.source} (its stamp says so): edit ${s.source}, then run make gen`);
}

/** One block of a page body: its name and where it runs, `##` line to the next `#` or `##`. */
export interface Span {
  readonly name: string;
  readonly start: number;
  readonly end: number;
}

/** Every block of a body, in page order. */
export function blockSpans(body: string): Span[] {
  const { tree } = parseKb(body);
  const heads = tree.children.filter((n): n is Heading => n.type === 'heading' && n.depth <= 2);
  const out: Span[] = [];
  heads.forEach((h, i) => {
    const name = h.depth === 2 ? readKb(h)?.facts?.['block'] : undefined;
    if (name === undefined) return;
    const next = heads[i + 1];
    // Every node of a parsed tree carries its position.
    out.push({ name, start: h.position?.start.offset as number, end: next === undefined ? body.length : (next.position?.start.offset as number) });
  });
  return out;
}

/**
 * The body with block `name` set to `lines` (its `##` line first), or taken
 * out when `lines` is null. An existing block is replaced where it stands (the
 * last of that name, as the reader keeps it); a new one goes before the first
 * block that `order` — the kind's block order — puts after it, or at the end.
 */
export function putBlock(body: string, name: string, lines: readonly string[] | null, order: readonly string[]): string {
  const spans = blockSpans(body);
  const at = [...spans].reverse().find((s) => s.name === name);
  if (lines === null) {
    if (at === undefined) return body;
    const headPart = body.slice(0, at.start);
    const tail = body.slice(at.end);
    return tail === '' ? headPart.replace(/\n+$/, '\n') : headPart + tail;
  }
  const md = lines.join('\n');
  if (at !== undefined) return `${body.slice(0, at.start)}${md}\n${at.end < body.length ? '\n' : ''}${body.slice(at.end)}`;
  const later = order.slice(order.indexOf(name) + 1);
  const next = spans.find((s) => later.includes(s.name));
  if (next !== undefined) return `${body.slice(0, next.start)}${md}\n\n${body.slice(next.start)}`;
  return `${body.replace(/\n*$/, '')}\n\n${md}\n`;
}
