/**
 * The claim gate: the command claims in shell fences hold against the tree,
 * and nothing that is not a claim — a marked block, an unlabelled fence, an
 * inline span, a placeholder — is judged as one.
 */

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { CLAIMS_MAKEFILE, claimsTree } from '../lib/fixtures.js';
import { capture, expectFail, expectMisuse, expectPass, makeSandbox, REPO_ROOT, type Sandbox } from '../lib/sandbox.js';
import {
  commandLines,
  isClaimFile,
  isPlaceholder,
  isStamped,
  judge,
  makeTargets,
  openQuote,
  scanFile,
  simpleCommands,
  spec,
} from './check-claims.js';

let sb: Sandbox;
beforeEach(() => {
  sb = makeSandbox();
  claimsTree(sb);
});
afterEach(() => sb.cleanup());

const findings = (err: string): string[] => err.split('\n').filter((l) => l.startsWith('[claims] FAIL'));
const fence = (label: string, lines: readonly string[]): string => `\`\`\`${label}\n${lines.join('\n')}\n\`\`\`\n`;

describe('truth-sweep-O1', () => {
  it('a real target, a missing target, a nonexistent gate and a missing path: three findings, the repeats draw nothing', async () => {
    const stale = ['make nope', 'make gate G=check-nope', 'node scripts/gone.mjs'];
    const page = [
      '# A page',
      '',
      fence('bash', ['make build', ...stale]),
      '<!-- demo:start -->',
      fence('bash', stale),
      '<!-- demo:end -->',
      '',
      fence('', stale),
      'Run `make nope`, `make gate G=check-nope` and `node scripts/gone.mjs` in prose.',
      '',
      fence('bash', ['make <target>', 'make gate G=<stem>', 'node scripts/<name>.mjs']),
    ].join('\n');
    sb.write('docs/page.md', page);

    const r = await sb.run(spec);
    expectFail(r);
    expect(r.out).toBe('');
    expect(findings(r.err)).toEqual([
      '[claims] FAIL docs/page.md:5: `make nope` — the Makefile has no target nope',
      '[claims] FAIL docs/page.md:6: `make gate G=check-nope` — no gate or generator check-nope.ts under tools/src/gates or tools/src/gen',
      '[claims] FAIL docs/page.md:7: `node scripts/gone.mjs` — scripts/gone.mjs is not on disk',
    ]);

    sb.write('tools/src/gates/check-nope.ts', '// a gate\n');
    sb.write('scripts/gone.mjs', '// a script\n');
    sb.write('Makefile', `${CLAIMS_MAKEFILE}\nnope:\n\t@true\n`);
    const fixed = await sb.run(spec);
    expectPass(fixed);
    expect(fixed.err).toBe('');
    expect(fixed.out.split('\n')).toHaveLength(1);
  });
});

describe('what it reads', () => {
  it('reads top-level markdown, pages under docs/, every CLAUDE.md and the harness markdown', async () => {
    for (const f of ['NOTES.md', 'docs/a/b.md', 'tools/CLAUDE.md', '.claude/skills/x/SKILL.md', '.claude/rules/r.md']) {
      sb.write(f, fence('bash', ['make nope']));
    }
    const r = await sb.run(spec);
    expect(findings(r.err).map((l) => l.split(':')[0])).toEqual([
      '[claims] FAIL .claude/rules/r.md',
      '[claims] FAIL .claude/skills/x/SKILL.md',
      '[claims] FAIL NOTES.md',
      '[claims] FAIL docs/a/b.md',
      '[claims] FAIL tools/CLAUDE.md',
    ]);
  });

  it('leaves other markdown and a stamped file alone', async () => {
    sb.write('plans/plan.md', fence('bash', ['make nope']));
    sb.write('scripts/notes.md', fence('bash', ['make nope']));
    sb.write(
      'docs/reference/gates.md',
      `<!-- GENERATED by tools/src/gen/gen-gates.ts from docs/data/gates.json. Do not edit this file. -->\n\n${fence('bash', ['make nope'])}`,
    );
    expectPass(await sb.run(spec));
    expect(isClaimFile('site/index.html')).toBe(false);
  });

  it('reads sh, shell, zsh, console and shell-session fences too, the last two only at their prompts', async () => {
    sb.write(
      'docs/a.md',
      `${fence('sh', ['make nope'])}${fence('console', ['$ make gone', 'make output-line'])}${fence('shell-session', ['$ make lost', 'make output-line'])}`,
    );
    const r = await sb.run(spec);
    expect(findings(r.err)).toEqual([
      '[claims] FAIL docs/a.md:2: `make nope` — the Makefile has no target nope',
      '[claims] FAIL docs/a.md:5: `make gone` — the Makefile has no target gone',
      '[claims] FAIL docs/a.md:9: `make lost` — the Makefile has no target lost',
    ]);
  });

  it('reads a page that only quotes the stamp, and skips one whose stamp sits below its frontmatter', async () => {
    const stamp = '<!-- GENERATED by tools/src/gen/x.ts from docs/data/x.json. Do not edit this file. -->';
    sb.write('docs/quotes.md', `# Stamps\n\nA generated page opens with \`${stamp}\`.\n\n${fence('markdown', [stamp])}${fence('bash', ['make nope'])}`);
    sb.write('docs/reference/deep.md', `---\ntitle: x\n---\n\n${stamp}\n\n${fence('bash', ['make nope'])}`);
    const r = await sb.run(spec);
    expect(findings(r.err)).toEqual(['[claims] FAIL docs/quotes.md:9: `make nope` — the Makefile has no target nope']);
    expect(isStamped(`x\n  ${stamp}  \n`)).toBe(true);
    expect(isStamped(`\`\`\`\n${stamp}\n\`\`\`\n`)).toBe(false);
    expect(isStamped(stamp.replace('this file', 'this table'))).toBe(false);
  });

  it('starts a marked block only at a marker on a line of its own, and names one never closed', async () => {
    sb.write(
      'docs/marks.md',
      [
        'A marked block (`<!-- name:start -->`) is filled by its generator.',
        '',
        fence('bash', ['make nope']),
        '<!--tight:start-->',
        fence('bash', ['make skipped']),
        '  <!--  tight:end  -->',
        fence('bash', ['make gone']),
        '<!-- open:start -->',
        fence('bash', ['make unread']),
      ].join('\n'),
    );
    const r = await sb.run(spec);
    expect(findings(r.err)).toEqual([
      '[claims] FAIL docs/marks.md:4: `make nope` — the Makefile has no target nope',
      '[claims] FAIL docs/marks.md:14: `make gone` — the Makefile has no target gone',
      '[claims] FAIL docs/marks.md:17: <!-- open:start --> has no <!-- open:end --> on a line of its own, so nothing after it is read',
    ]);
    expect(scanFile('<!-- a:start -->\n<!-- a:end -->\n').unclosed).toBeNull();
  });

  it('silences a line that opts out, and drops a leading prompt elsewhere', async () => {
    claimsTree(sb, ['make nope   # claim-ok: defined in another checkout', '$ make build']);
    expectPass(await sb.run(spec));
  });

  it('names the missing Makefile itself', async () => {
    sb.rm('Makefile');
    expectFail(await sb.run(spec), '`make build` — the tree has no Makefile');
  });
});

describe('make', () => {
  const lacks = (text: string): (string | null)[] => judge(sb.dir, text, makeTargets(CLAIMS_MAKEFILE)).map((c) => c.lacks);

  it('stops reading targets at the first word that is not one', () => {
    expect(lacks('make build FOO=1 nope')).toEqual([null]);
    expect(lacks('make build <target> nope')).toEqual([null]);
    expect(lacks('make -j4 --no-print-directory build nope')).toEqual([null, 'the Makefile has no target nope']);
  });

  it('reads a flag’s value as the flag’s, not as a target', () => {
    expect(lacks('make -j 4 build')).toEqual([null]);
    expect(lacks('make --jobs 4 build nope')).toEqual([null, 'the Makefile has no target nope']);
    expect(lacks('make -l 2.5 -o stale.o -W x.c build')).toEqual([null]);
    expect(lacks('make -j build')).toEqual([null]);
    expect(lacks('make -k nope')).toEqual(['the Makefile has no target nope']);
  });

  it('judges nothing in a line that is only a prefix or an assignment, or a flag missing its value', () => {
    expect(lacks('FOO=1')).toEqual([]);
    expect(lacks('time')).toEqual([]);
    expect(lacks('make -j')).toEqual([]);
  });

  it('reads past a command prefix to the make it runs', () => {
    for (const prefix of ['time', 'nohup', 'nice -n 5', 'xargs -0', 'xargs -I {}', 'exec', 'command', 'env -u X', 'sudo -u me', 'FOO=1']) {
      expect(lacks(`${prefix} make nope`), prefix).toEqual(['the Makefile has no target nope']);
    }
  });

  it('skips a make run against another directory or file', () => {
    expect(lacks('make -C site nope')).toEqual([]);
    expect(lacks('make -f other.mk nope')).toEqual([]);
  });

  it('judges each command of a compound line, and nothing after a cd', () => {
    expect(lacks('make build && make nope; make build | cat')).toEqual([null, 'the Makefile has no target nope', null]);
    expect(lacks('make build && cd tools && make nope')).toEqual([null]);
    expect(lacks('(cd site && make nope)')).toEqual([]);
  });

  it('reads the Makefile’s targets, and not its variables, patterns or specials', () => {
    const t = makeTargets('X := 1\n.PHONY: a\na b: c\n\t@x\n$(STAMP): y\n%.o: %.c\nd::\n# e:\n');
    expect([...t].sort()).toEqual(['a', 'b', 'd']);
  });
});

describe('programs', () => {
  beforeEach(() => {
    sb.write('scripts/real.mjs', '');
    sb.write('tests/run.sh', '');
  });
  const lacks = (text: string): (string | null)[] => judge(sb.dir, text, null).map((c) => c.lacks);

  it('judges the program a runner runs', () => {
    expect(lacks('node scripts/real.mjs --flag')).toEqual([null]);
    expect(lacks('node --test scripts/gone.mjs')).toEqual(['scripts/gone.mjs is not on disk']);
    expect(lacks('bash tests/run.sh sync')).toEqual([null]);
    expect(lacks('sh ./tests/gone.sh')).toEqual(['tests/gone.sh is not on disk']);
    expect(lacks('npx tsx tools/src/gone.ts')).toEqual(['tools/src/gone.ts is not on disk']);
    expect(lacks('node_modules/.bin/tsx tools/src/gates/check-gone.ts')).toEqual(['tools/src/gates/check-gone.ts is not on disk']);
    expect(lacks('node --import x.mjs scripts/real.mjs')).toEqual([null]);
    expect(lacks('python3 scripts/gone.py')).toEqual(['scripts/gone.py is not on disk']);
    expect(lacks('python -u tests/run.sh')).toEqual([null]);
    expect(lacks('nohup node scripts/gone.mjs')).toEqual(['scripts/gone.mjs is not on disk']);
  });

  it('judges a path written as the command itself, but not an installed binary', () => {
    expect(lacks('./tests/run.sh -v')).toEqual([null]);
    expect(lacks('scripts/gone.sh')).toEqual(['scripts/gone.sh is not on disk']);
    expect(lacks('node_modules/.bin/vitest run')).toEqual([]);
  });

  it('skips inline code, placeholders, globs, variables and absolute paths', () => {
    expect(lacks("node -e 'console.log(1)'")).toEqual([]);
    expect(lacks('node scripts/<name>.mjs')).toEqual([]);
    expect(lacks('node --test scripts/test/*.test.mjs')).toEqual([]);
    expect(lacks('bash "$HOOK"')).toEqual([]);
    expect(lacks('bash /usr/local/bin/x.sh')).toEqual([]);
    expect(lacks('env FOO=1 sudo node scripts/gone.mjs')).toEqual(['scripts/gone.mjs is not on disk']);
  });

  it('judges nothing in a command it does not know', () => {
    expect(lacks('git show HEAD:scripts/gone.mjs > scripts/gone.mjs')).toEqual([]);
    expect(lacks('grep -rn "make nope" docs')).toEqual([]);
  });
});

describe('commandLines', () => {
  it('joins a continued command and reports it at its first line', () => {
    expect(commandLines(fence('bash', ['node scripts/kb.mjs production x \\', '  --knobs "[]"']))).toEqual([
      { line: 2, text: 'node scripts/kb.mjs production x --knobs "[]"' },
    ]);
  });

  it('skips a heredoc body and the lines inside a quote left open', () => {
    const lines = commandLines(
      fence('bash', ["cat > f <<'EOF'", 'make nope', 'EOF', "node -e '", 'make nope', "'", 'make build']),
    ).map((c) => c.text);
    expect(lines).toEqual(["cat > f <<'EOF'", "node -e '", 'make build']);
  });

  it('ends a fence only at a closing run as long as its opening, and skips comment lines', () => {
    const text = '````bash\n# a comment\n```\nmake build\n````\n';
    expect(commandLines(text).map((c) => c.text)).toEqual(['```', 'make build']);
  });
});

describe('the small readers', () => {
  it('tracks an open quote, stopping at a comment', () => {
    expect(openQuote("node -e '")).toBe("'");
    expect(openQuote('echo "a \\" b')).toBe('"');
    expect(openQuote("echo 'x' # it's")).toBeNull();
    expect(openQuote("x'", "'")).toBeNull();
  });

  it('splits on unquoted separators only', () => {
    const cmds = simpleCommands('a "x && y" && b \'c;d\' ; e | f & g `h` # tail').map((ws) => ws.map((w) => w.text).join(' '));
    expect(cmds).toEqual(['a x && y', 'b c;d', 'e', 'f', 'g', 'h']);
  });

  it('honours a backslash outside quotes and inside double quotes, and an unclosed double quote', () => {
    expect(openQuote("echo it\\'s")).toBeNull();
    expect(simpleCommands('a\\ b "c \\" d" "open').map((ws) => ws.map((w) => w.text))).toEqual([['a b', 'c \\" d', 'open']]);
  });

  it('knows a placeholder', () => {
    for (const w of ['<id>', '…', 'a...b', '*.md', '$X', '~/x', '{a,b}', '[x]']) expect(isPlaceholder(w), w).toBe(true);
    for (const w of ['scripts/kb.mjs', 'build', 'G=check-json']) expect(isPlaceholder(w), w).toBe(false);
  });
});

describe('misuse', () => {
  it('takes no arguments and writes nothing', async () => {
    const before = sb.snapshot();
    expectMisuse(await sb.run(spec, ['--nope']));
    expectMisuse(await sb.run(spec, ['README.md']));
    expect(sb.snapshot()).toEqual(before);
  });
});

describe('the real tree', () => {
  it('holds every command claim, and reads a claim at all', async () => {
    const r = await capture(spec, [], REPO_ROOT);
    expect(r.err).toBe('');
    expectPass(r);
    expect(Number(/(\d+) command claims/.exec(r.out)?.[1] ?? 0)).toBeGreaterThan(0);
  });
});
